version: "3.4"
services:
  zeek: 
    image: registry2.lagoni.co.uk/lagoni-engineering/zeek-kf:dev
    stdin_open: true
    tty: true
    build:
      network: host
      dockerfile: Dockerfile
      context: "./"
    privileged: true
    command: ["-B", "dpd", "-i", "en0"]
