# SPDX-FileCopyrightText: 2020 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT
---
services:
  zeek:
    image: ghcr.io/fouwels/zethernet:dev
    network_mode: host
    build:
      dockerfile: Dockerfile
      context: "./"
    command: [ "-B", "dpd", "-i", "eth0" ]
