# Generated by binpac_quickstart

refine flow ENIPLG_Flow += {
	function enip_list_identity(list_identity: List_Identity): bool 
		%{
		printf("Vendor %d\nProduct %s\n",		    ${list_identity.vendor},
													std_str(${list_identity.product_name}).c_str());

	 	BifEvent::generate_eniplg_event(connection()->bro_analyzer(), connection()->bro_analyzer()->Conn());

		return true;
		%}	
};

refine typeattr List_Identity += &let {
    proc: bool = $context.flow.enip_list_identity(this);
    };